/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Model;

import javax.swing.JOptionPane;

/**
 *
 * @author kien5
 */
public class MenuForm extends javax.swing.JFrame {

    /**
     * Creates new form MenuForm
     */
    public MenuForm() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_QuanLiTaiSan = new javax.swing.JButton();
        QuanLiHoatDong = new javax.swing.JButton();
        btn_QuanLiSVHD = new javax.swing.JButton();
        btn_TKBC = new javax.swing.JButton();
        btn_CSVC = new javax.swing.JButton();
        btn_QLTaiKhoan = new javax.swing.JButton();
        btn_Thoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("Chức Năng Của Hệ Thống");

        btn_QuanLiTaiSan.setBackground(new java.awt.Color(153, 255, 255));
        btn_QuanLiTaiSan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_QuanLiTaiSan.setForeground(new java.awt.Color(0, 153, 153));
        btn_QuanLiTaiSan.setText("Quản Lí Thành Viên");
        btn_QuanLiTaiSan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QuanLiTaiSanActionPerformed(evt);
            }
        });

        QuanLiHoatDong.setBackground(new java.awt.Color(153, 255, 255));
        QuanLiHoatDong.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        QuanLiHoatDong.setForeground(new java.awt.Color(0, 153, 153));
        QuanLiHoatDong.setText("Quản Lí Hoạt Động");
        QuanLiHoatDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuanLiHoatDongActionPerformed(evt);
            }
        });

        btn_QuanLiSVHD.setBackground(new java.awt.Color(153, 255, 255));
        btn_QuanLiSVHD.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_QuanLiSVHD.setForeground(new java.awt.Color(0, 153, 153));
        btn_QuanLiSVHD.setText("Quản Lí Sinh Viên Tham Gia HĐ");
        btn_QuanLiSVHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QuanLiSVHDActionPerformed(evt);
            }
        });

        btn_TKBC.setBackground(new java.awt.Color(153, 255, 255));
        btn_TKBC.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_TKBC.setForeground(new java.awt.Color(0, 153, 153));
        btn_TKBC.setText("Thống Kê / Báo Cáo");
        btn_TKBC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TKBCActionPerformed(evt);
            }
        });

        btn_CSVC.setBackground(new java.awt.Color(153, 255, 255));
        btn_CSVC.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_CSVC.setForeground(new java.awt.Color(0, 153, 153));
        btn_CSVC.setText("Quản Lí Cơ Sở Vật Chất");
        btn_CSVC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CSVCActionPerformed(evt);
            }
        });

        btn_QLTaiKhoan.setBackground(new java.awt.Color(153, 255, 255));
        btn_QLTaiKhoan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_QLTaiKhoan.setForeground(new java.awt.Color(0, 153, 153));
        btn_QLTaiKhoan.setText("Quản Lí Tài Khoản");
        btn_QLTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QLTaiKhoanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_QuanLiSVHD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(QuanLiHoatDong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_QuanLiTaiSan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_CSVC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_TKBC, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(49, 49, 49))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_QLTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btn_QuanLiTaiSan, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(QuanLiHoatDong, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_QuanLiSVHD, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_CSVC, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_TKBC, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_QLTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        btn_Thoat.setBackground(new java.awt.Color(153, 255, 255));
        btn_Thoat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_Thoat.setForeground(new java.awt.Color(0, 153, 153));
        btn_Thoat.setText("Thoát");
        btn_Thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThoatActionPerformed
        
            setVisible(false);
            DangNhapForm a = new DangNhapForm();
            a.setVisible(true);
        
        
        
    }//GEN-LAST:event_btn_ThoatActionPerformed

    private void btn_QuanLiTaiSanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QuanLiTaiSanActionPerformed
        QuanLiThanhVien_ITF a= new QuanLiThanhVien_ITF();
        a.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btn_QuanLiTaiSanActionPerformed

    private void QuanLiHoatDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuanLiHoatDongActionPerformed
        QuanLiHD_ITF a = new QuanLiHD_ITF();
        a.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_QuanLiHoatDongActionPerformed

    private void btn_CSVCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CSVCActionPerformed
        QuanLiCoSoVatChat_ITF a= new QuanLiCoSoVatChat_ITF();
        a.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btn_CSVCActionPerformed

    private void btn_QuanLiSVHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QuanLiSVHDActionPerformed
        HoatDong_SinhVien_ITF a= new HoatDong_SinhVien_ITF();
        a.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_btn_QuanLiSVHDActionPerformed

    private void btn_QLTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QLTaiKhoanActionPerformed
        QuanLiTaiKhoan_ITF a= new QuanLiTaiKhoan_ITF();
        a.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btn_QLTaiKhoanActionPerformed

    private void btn_TKBCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TKBCActionPerformed
        BaoCao_ITF a= new BaoCao_ITF();
        a.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btn_TKBCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable(){
            public void run() {
                new MenuForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton QuanLiHoatDong;
    private javax.swing.JButton btn_CSVC;
    private javax.swing.JButton btn_QLTaiKhoan;
    private javax.swing.JButton btn_QuanLiSVHD;
    private javax.swing.JButton btn_QuanLiTaiSan;
    private javax.swing.JButton btn_TKBC;
    private javax.swing.JButton btn_Thoat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
