/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Model;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kien5
 */
public class QuanLiCoSoVatChat_ITF extends javax.swing.JFrame {

    /**
     * Creates new form QuanLiCoSoVatChat_ITF
     */
     public ArrayList<QuanLiCoSoVatChat_Class> dsvc = new ArrayList<>();

    public QuanLiCoSoVatChat_ITF() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public void LoadFile() {
        try {
            FileInputStream fis = new FileInputStream("CSVC.txt");
            ObjectInputStream ois = new ObjectInputStream(fis);
            var resultList = (ArrayList) ois.readObject();
            dsvc = resultList;
            ois.close();
            fis.close();
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }
    }

    public void reset() {
        LoadFile();
        JTable table = new JTable();
        DefaultTableModel model = new DefaultTableModel();
        Object[] columnNames = {"Mã Vật Tư", "Tên Vật Tư", "Tình Trạng", "Số lượng", "Kinh Phí", "Độ khan hiếm"};
        model.setColumnIdentifiers(columnNames);
        Object[][] rowData = new Object[dsvc.size()][7];
        for (int i = 0; i < dsvc.size(); i++) {
            rowData[i][0] = dsvc.get(i).getMaVatTu();
            rowData[i][1] = dsvc.get(i).getTenVatTu();
            rowData[i][2] = dsvc.get(i).getTinhTrang();
            rowData[i][3] = dsvc.get(i).getSoLuong();
            rowData[i][4] = dsvc.get(i).getKinhPhi();
            rowData[i][5] = dsvc.get(i).getDoKhanHiem();
        }
        model.setDataVector(rowData, columnNames);
        this.table.setModel(model);
        this.add(new JScrollPane(table));
        this.pack();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txttenvt = new javax.swing.JTextField();
        txtmavt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtsoluong = new javax.swing.JTextField();
        btn_Them = new javax.swing.JButton();
        btn_Sua = new javax.swing.JButton();
        btn_Xoa = new javax.swing.JButton();
        btn_Reset = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtKinhPhi = new javax.swing.JTextField();
        cbx_tinhtrang = new javax.swing.JComboBox<>();
        btn_Thoat = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Số lượng");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Mã Vật Tư");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Tên Vật Tư");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Tình trạng");

        btn_Them.setBackground(new java.awt.Color(153, 255, 255));
        btn_Them.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Them.setText("Thêm");
        btn_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemActionPerformed(evt);
            }
        });

        btn_Sua.setBackground(new java.awt.Color(153, 255, 255));
        btn_Sua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Sua.setText("Sửa");
        btn_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaActionPerformed(evt);
            }
        });

        btn_Xoa.setBackground(new java.awt.Color(153, 255, 255));
        btn_Xoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Xoa.setText("Xóa");
        btn_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaActionPerformed(evt);
            }
        });

        btn_Reset.setBackground(new java.awt.Color(153, 255, 255));
        btn_Reset.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Reset.setText("Reset");
        btn_Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ResetActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Kinh phí");

        cbx_tinhtrang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbx_tinhtrang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mới", "Cũ ", "Hư Hỏng" }));

        btn_Thoat.setBackground(new java.awt.Color(153, 255, 255));
        btn_Thoat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Thoat.setText("Thoát");
        btn_Thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtmavt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_Them, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txttenvt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_Sua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cbx_tinhtrang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtsoluong, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_Reset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_Xoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtKinhPhi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Thoat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtmavt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txttenvt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(btn_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_tinhtrang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(txtKinhPhi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_Thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã Vật tư", "Tên Vật Tư", "Tình Trạng", "Số lượng", "Kinh Phí", "Độ khan hiếm"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tableAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 255));
        jLabel1.setText("Quản Lí  Cơ Sở Vật Chất CLB Fit-Media");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ResetActionPerformed
        txtmavt.setText("");
        txttenvt.setText("");
        txtKinhPhi.setText("");
        txtsoluong.setText("");
        cbx_tinhtrang.setSelectedIndex(0);
        reset();
    }//GEN-LAST:event_btn_ResetActionPerformed

    private void tableAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tableAncestorAdded
        reset();
    }//GEN-LAST:event_tableAncestorAdded

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        int row = table.rowAtPoint(evt.getPoint());
        String MaVT = (String) table.getValueAt(row, 0);
        String TenVT = (String) table.getValueAt(row, 1);
        int SoLuong = (int) table.getValueAt(row, 3);
        long KinhPhi = (long) table.getValueAt(row, 4);
        String TinhTrang = (String) table.getValueAt(row, 2);
        txtmavt.setText(MaVT);
        txttenvt.setText(TenVT);
        if (TinhTrang.equals("Mới")) {
            cbx_tinhtrang.setSelectedIndex(0);
        }
        if (TinhTrang.equals("Cũ")) {
            cbx_tinhtrang.setSelectedIndex(1);
        }
        if (TinhTrang.equals("Hư Hỏng")) {
            cbx_tinhtrang.setSelectedIndex(2);
        }
        txtsoluong.setText(String.valueOf(SoLuong));
        txtKinhPhi.setText(String.valueOf(KinhPhi));


    }//GEN-LAST:event_tableMouseClicked

    private void btn_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemActionPerformed
        LoadFile();
        String MaVT = txtmavt.getText();
        String TenVT = txttenvt.getText();
        String TinhTrang;
        int tinhtrang = cbx_tinhtrang.getSelectedIndex();
        if (tinhtrang == 0 || tinhtrang == -1) {
            TinhTrang = "Mới";
        } else if (tinhtrang == 1) {
            TinhTrang = "Cũ";
        } else {
            TinhTrang = "Hư Hỏng";
        }

        String SoLuong = txtsoluong.getText();
        String KinhPhi = txtKinhPhi.getText();
        int Soluong1 = 0;
        long KinhPhi1 = 0;
        boolean check = false;
        for (QuanLiCoSoVatChat_Class item : dsvc) {
            if (item.getMaVatTu().equals(MaVT)) {
                check = true;
                break;
            }

        }
        if (check) {
            JOptionPane.showMessageDialog(rootPane, "Trùng 1 mã vật tư");

        } else {
            if (MaVT.isEmpty() || TenVT.isEmpty() || SoLuong.isEmpty() || KinhPhi.isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "Không được để trống 1 trong các dữ liệu");
            } else {
                boolean check1 = false;
                try {
                    Soluong1 = Integer.parseInt(SoLuong);
                    KinhPhi1 = Long.parseLong(KinhPhi);
                    check1 = true;
                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(rootPane, "Số lượng / Kinh phí phải là 1 con số");
                }
                if (check1) {
                    String KhanHiem;
                    if (Soluong1 <= 5) {
                        KhanHiem = "Rất Khan Hiêm";
                    } else if (Soluong1 >= 6 && Soluong1 <= 10) {
                        KhanHiem = "Khan Hiếm";
                    } else {
                        KhanHiem = "Bình THường";
                    }
                    dsvc.add(new QuanLiCoSoVatChat_Class(MaVT, TenVT, TinhTrang, Soluong1, KinhPhi1, KhanHiem));
                    try {
                        FileOutputStream fos = new FileOutputStream("CSVC.txt");
                        ObjectOutputStream oos = new ObjectOutputStream(fos);
                        oos.writeObject(dsvc);
                        oos.close();
                        fos.close();
                    } catch (FileNotFoundException e) {
                        e.printStackTrace();
                    } catch (IOException e) {
                        e.printStackTrace();
                    }
                    txtmavt.setText("");
                    txttenvt.setText("");
                    txtKinhPhi.setText("");
                    txtsoluong.setText("");
                    cbx_tinhtrang.setSelectedIndex(0);
                    reset();
                    JOptionPane.showMessageDialog(rootPane, "Them Thanh Cong");
                }
            }
        }
    }//GEN-LAST:event_btn_ThemActionPerformed

    private void btn_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaActionPerformed
        LoadFile();
        String MaVT = txtmavt.getText();
        String TenVT = txttenvt.getText();
        String TinhTrang;
        int tinhtrang = cbx_tinhtrang.getSelectedIndex();
        if (tinhtrang == 0 || tinhtrang == -1) {
            TinhTrang = "Mới";
        } else if (tinhtrang == 1) {
            TinhTrang = "Cũ";
        } else {
            TinhTrang = "Hư Hỏng";
        }

        String SoLuong = txtsoluong.getText();
        String KinhPhi = txtKinhPhi.getText();
        int Soluong1 = 0;
        long KinhPhi1 = 0;
        boolean check = false;
        for (QuanLiCoSoVatChat_Class item : dsvc) {
            if (item.getMaVatTu().equals(MaVT)) {
                check = true;
                break;
            }

        }
        if (!check) {
            JOptionPane.showMessageDialog(rootPane, "Trùng 1 mã vật tư");

        } else {
            if (MaVT.isEmpty() || TenVT.isEmpty() || SoLuong.isEmpty() || KinhPhi.isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "Không được để trống 1 trong các dữ liệu");
            } else {
                boolean check1 = false;
                try {
                    Soluong1 = Integer.parseInt(SoLuong);
                    KinhPhi1 = Long.parseLong(KinhPhi);
                    check1 = true;
                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(rootPane, "Số lượng / Kinh phí phải là 1 con số");
                }
                if (check1) {
                    String KhanHiem;
                    if (Soluong1 <= 5) {
                        KhanHiem = "Rất Khan Hiêm";
                    } else if (Soluong1 >= 6 && Soluong1 <= 10) {
                        KhanHiem = "Khan Hiếm";
                    } else {
                        KhanHiem = "Bình THường";
                    }
                    for (QuanLiCoSoVatChat_Class item : dsvc) {
                        if (item.getMaVatTu().equals(MaVT)) {
                            item.TenVatTu = TenVT;
                            item.KinhPhi = KinhPhi1;
                            item.SoLuong = Soluong1;
                            item.TinhTrang = TinhTrang;
                            item.DoKhanHiem = KhanHiem;
                            break;
                        }
                    }
                    try {
                        FileOutputStream fos = new FileOutputStream("CSVC.txt");
                        ObjectOutputStream oos = new ObjectOutputStream(fos);
                        oos.writeObject(dsvc);
                        oos.close();
                        fos.close();
                    } catch (FileNotFoundException e) {
                        e.printStackTrace();
                    } catch (IOException e) {
                        e.printStackTrace();
                    }
                    txtmavt.setText("");
                    txttenvt.setText("");
                    txtKinhPhi.setText("");
                    txtsoluong.setText("");
                    cbx_tinhtrang.setSelectedIndex(0);
                    reset();
                    JOptionPane.showMessageDialog(rootPane, "Sua Thanh Cong");
                }
            }
        }
    }//GEN-LAST:event_btn_SuaActionPerformed

    private void btn_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaActionPerformed
        String MaVT = txtmavt.getText();
        if (MaVT.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Không đc để trống Mã Vật Tư");
        } else {
            boolean check = false;
            for (QuanLiCoSoVatChat_Class item : dsvc) {
                if (item.getMaVatTu().equals(MaVT)) {
                    check = true;
                    break;
                }
            }
            if (!check) {
                JOptionPane.showMessageDialog(rootPane, "Không trùng Mã Vật Tư");
            } else {
                for (QuanLiCoSoVatChat_Class item : dsvc) {
                    if (item.getMaVatTu().equals(MaVT)) {
                        dsvc.remove(item);
                        break;
                    }
                }
                try {
                    FileOutputStream fos = new FileOutputStream("CSVC.txt");
                    ObjectOutputStream oos = new ObjectOutputStream(fos);
                    oos.writeObject(dsvc);
                    oos.close();
                    fos.close();
                } catch (FileNotFoundException e) {
                    e.printStackTrace();
                } catch (IOException e) {
                    e.printStackTrace();
                }
                txtmavt.setText("");
                txttenvt.setText("");
                txtKinhPhi.setText("");
                txtsoluong.setText("");
                cbx_tinhtrang.setSelectedIndex(0);
                reset();
                JOptionPane.showMessageDialog(rootPane, "Xóa Thành Công");
            }
        }
    }//GEN-LAST:event_btn_XoaActionPerformed

    private void btn_ThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThoatActionPerformed

        int result = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn Thoát?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            // Người dùng chọn YES
            MenuForm a = new MenuForm();
            a.setVisible(true);
            setVisible(false);
        } else {
            JOptionPane.getRootFrame().dispose();
        }
    }//GEN-LAST:event_btn_ThoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLiCoSoVatChat_ITF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLiCoSoVatChat_ITF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLiCoSoVatChat_ITF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLiCoSoVatChat_ITF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLiCoSoVatChat_ITF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Reset;
    private javax.swing.JButton btn_Sua;
    private javax.swing.JButton btn_Them;
    private javax.swing.JButton btn_Thoat;
    private javax.swing.JButton btn_Xoa;
    private javax.swing.JComboBox<String> cbx_tinhtrang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtKinhPhi;
    private javax.swing.JTextField txtmavt;
    private javax.swing.JTextField txtsoluong;
    private javax.swing.JTextField txttenvt;
    // End of variables declaration//GEN-END:variables
}
